name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  check:
    name: make check
    if: github.repository == 'apple/coreai-optimization'
    runs-on: [self-hosted, macos, tahoe, ARM64]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false
      - run: make check

  macos-tests:
    name: macos / torch=highest / fast
    needs: [check]
    if: github.repository == 'apple/coreai-optimization'
    runs-on: [self-hosted, macos, tahoe, ARM64]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false
      - name: Run tests
        run: make test-highest-pytorch PYTEST_ARGS="--marker 'not slow' --junit"
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results-macos-highest-fast
          path: test-results/
